moneytransfer/administration/urls.py
from django.urls import path
from administration import views


app_name='administration'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('my-dashboard/', views.my_dashboard,name='my_dashboard'),
    path('logout/', views.logoutUser, name="logout"),
    path('agent/',views.agent_list,name='agent'),
    path('add-new-agent/', views.new_agent,name='add-new-agent'),
    path('view-agent/<int:id>', views.view_agent,name='view_agent'),
    path('edit-agent/<int:id>/', views.edit_agent,name='edit_agent'), # get and post req. for update operation
    path('edit-agent-admin-profile/',views.agentprofile, name='agent_profile'),
    path('edit-customer-admin-profile/',views.customerprofile, name='customer_profile'),
    path('agent-profile-change-password', views.agentchangepassword, name='agent_change_password'),
    path('customer-profile-change-password', views.customerchangepassword, name='customer_change_password'),
    path('delete-agent/delete/<int:id>/',views.delete_agent,name='delete_agent'),
    path('customer/', views.customer_list,name='customer'),
    path('add-new-customer/', views.new_customer,name='add-new-customer'),
    path('view-customer/<int:id>', views.view_customer,name='view_customer'),
    path('edit-customer/<int:id>/', views.edit_customer,name='edit_customer'), # get and post req. for update operation
    path('delete-customer/delete/<int:id>/',views.delete_customer,name='delete_customer'),
    path('currency/', views.currency_list,name='currency'),
    path('add-currency/', views.new_currency,name='add-currency'),
    path('view-currency/<int:id>', views.view_currency,name='view_currency'),
    path('edit-currency/<int:id>/', views.edit_currency,name='edit_currency'), # get and post req. for update operation
    path('delete-currency/delete/<int:id>/',views.delete_currency,name='delete_currency'),
    path('agent-bank/', views.agent_bank,name='agent_bank'),
    path('add-agent-bank/', views.add_agentbank,name='add_agent_bank'),
    path('view-agent-bank/<int:id>', views.view_agentbank,name='view_agent_bank'),
    path('edit-agent-bank/<int:id>/', views.edit_agentbank,name='edit_agent_bank'), # get and post req. for update operation
    path('delete-agent-bank/delete/<int:id>/',views.delete_agentbank,name='delete_agent_bank'),
    path('customer-bank/', views.customer_bank,name='customer_bank'),
    path('add-customer-bank/', views.add_customerbank,name='add_customer_bank'),
    path('view-customer-bank/<int:id>', views.view_customerbank,name='view_customer_bank'),
    path('edit-customer-bank/<int:id>/', views.edit_customerbank,name='edit_customer_bank'), # get and post req. for update operation
    path('delete-customer-bank/delete/<int:id>/',views.delete_customerbank,name='delete_customer_bank'),
    path('reason/',views.reason_list,name='reason'),
    path('add-reason/', views.new_reason,name='new_reason'),
    path('view-reason/<int:id>', views.view_reason,name='view_reason'),
    path('edit-reason/<int:id>/', views.edit_reason,name='edit_reason'), # get and post req. for update operation
    path('delete-reason/delete/<int:id>/',views.delete_reason,name='delete_reason'),
    path('faq/',views.faq_list,name='faq_list'),
    path('add-faq/', views.add_faq,name='add_faq'),
    path('edit-faq/<int:id>/', views.edit_faq,name='edit_faq'), # get and post req. for update operation
    path('delete-faq/delete/<int:id>/',views.delete_faq,name='delete_faq'),
    path('search/',views.GlobalSearchView,name='search'),




]

moneytransfer/exchange/urls.py
from django.urls import path
from exchange import views

app_name='exchange'

urlpatterns = [
    path('money-exchange/',views.exchange_list,name='money_exchange'),
    path('new-money-exchange/', views.new_exchange,name='new_money_exchange'),
    path('view-money-exchange/<int:id>', views.view_exchange,name='view_exchange'),
    path('edit-exchange/<int:id>/', views.edit_exchange,name='edit_exchange'), # get and post req. for update operation
    path('delete-exchange/delete/<int:id>/',views.delete_exchange,name='delete_exchange'),

]

moneytransfer/moneytransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from administration import views as administration_views
from django.conf.urls import handler404, handler500
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('administration.urls', namespace='administration')),
    path('transfer/',include('transfer.urls', namespace='transfer')),
    path('exchange/',include('exchange.urls', namespace='exchange')),
    path('customer/',include('customeraccess.urls', namespace='customeraccess')),
    path('reset_password/', PasswordResetView.as_view(template_name="auth/password-reset.html"),
         name="password_reset"),
    path('reset_password/done/', PasswordResetDoneView.as_view(template_name="auth/password-reset-done.html"),
         name="password_reset_done"),
    path('reset_password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="auth/password-reset-confirm.html"),
         name="password_reset_confirm"),
    path('reset_password/complete/',
         PasswordResetCompleteView.as_view(template_name="auth/password-reset-complete.html"),
         name="password_reset_complete"),


    
    
]  



handler404 = administration_views.error_404
handler500 = administration_views.error_500

moneytransfer/transfer/forms.py
from transfer.models import MoneyTransfer, DebtTransfer
from administration.models import CurrencyRate, MoneyUser
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, HTML





class MoneyTransferForm(forms.ModelForm):
    
    total_commission = forms.ModelChoiceField(queryset=CurrencyRate.objects.all(), to_field_name="total_commission")
    class Meta:
        model = MoneyTransfer
        fields = ('sender_agent', 'receiver_agent', 'sender_cu', 'receiver_cu', 'send_method',
                  'receive_method', 'agent_bank', 'from_currency', 'to_currency', 'total_commission',
                  'transfer_rate', 'sending_amount', 'receiving_amount', 'paid_amount', 'due_date',
                  'outstanding_amount', 'total_payment', 'payment_status', 'reason_type', 'notification_type', 'notes')

        widgets = {
            'due_date': forms.DateInput(attrs={'type': 'date'}),
            'notes': forms.Textarea(attrs={'placeholder': 'Write Your Notes'}),

        }

        labels = {

            'sender_agent': 'Sender Agent',
            'receiver_cu': 'Receiver Customer',
            'receiver_agent': 'Receiver Agent',
            'sender_cu': 'Sender Customer',
            'send_method': 'Sending Method',
            'receive_method': 'Receiving Method',
            'from_currency': 'Sending Currency',
            'to_currency': 'Receiving Currency',
            'total_commission': 'Exchange Rate',
            'transfer_rate': 'Transfer Rate',
            'sending_amount': 'Sending Amount',
            'receiving_amount': 'Receiving Amount',
            'paid_amount': 'Paid Amount',
            'outstanding_amount': 'Outstanding Amount',
            'total_payment': 'Total Payment',
            'payment_status': 'Payment Status',
            'reason_type': 'Reason For Sending',
            'notification_type': 'Notification',
            'notes': 'Notes (optional) ',

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.fields['receiving_amount'].widget.attrs['readonly'] = True
        self.fields['outstanding_amount'].widget.attrs['readonly'] = True
        self.fields['total_payment'].widget.attrs['readonly'] = True
        self.helper.form_tag = False
        self.helper.use_custom_control = False
        self.fields['sender_agent'].queryset = MoneyUser.objects.filter(is_agent=True, is_active=True)
        self.fields['sender_cu'].queryset = MoneyUser.objects.filter(is_customer=True, is_active=True)
        self.fields['receiver_agent'].queryset = MoneyUser.objects.filter(is_agent=True, is_active=True)
        self.fields['receiver_cu'].queryset = MoneyUser.objects.filter(is_customer=True, is_active=True)

        if 'from_currency' in self.data:
            try:
                from_currency = int(self.data.get('from_currency'))
                self.fields['to_currency'].queryset = MoneyTransfer.objects.filter(from_currency=from_currency)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['to_currency'].queryset = self.instance.from_currency.to_currency_set
        

        if 'to_currency' in self.data:
            try:
                to_currency = int(self.data.get('to_currency'))
                self.fields['total_commission'].queryset = CurrencyRate.objects.filter(to_currency=to_currency)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['total_commission'].queryset = self.instance.to_currency.total_commission_set

        self.helper.layout = Layout(
            HTML("<br>"),
            HTML("<h6 class=card-title> Transaction Details </h6><hr>"),
            Row(
                Column('sender_agent', css_class='form-group col-md-4 mb-3'),
                Column('receiver_agent', css_class='form-group col-md-4 mb-3'),
                Column('send_method', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('sender_cu', css_class='form-group col-md-4 mb-3'),
                Column('receiver_cu', css_class='form-group col-md-4 mb-3'),
                Column('receive_method', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('agent_bank', css_class='form-group col-md-4 mb-3'),
                Column('from_currency', css_class='form-group col-md-4 mb-3'),
                Column('to_currency', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('total_commission', css_class='form-group col-md-4 mb-3'),
                Column('transfer_rate', css_class='form-group col-md-4 mb-3'),
                Column('sending_amount', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('receiving_amount', css_class='form-group col-md-4 mb-3'),
                Column('paid_amount', css_class='form-group col-md-4 mb-3'),
                Column('total_payment', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('outstanding_amount', css_class='form-group col-md-4 mb-3'),
                Column('due_date', css_class='form-group col-md-4 mb-3'),
                Column('payment_status', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('reason_type', css_class='form-group col-md-4 mb-3'),
                Column('notification_type', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            HTML("<br>"),
            HTML("<h6 class=card-title> Notes Information </h6><hr>"),
            Row(
                Column('notes', css_class='form-group col-md-8 mb-3'),
                css_class='row'
            ),

        )


class EditMoneyTransferForm(forms.ModelForm):
    total_commission = forms.ModelChoiceField(queryset=CurrencyRate.objects.all(), to_field_name="total_commission")

    class Meta:
        model = MoneyTransfer
        fields = ('sender_agent', 'receiver_agent', 'sender_cu', 'receiver_cu', 'send_method',
                  'receive_method', 'agent_bank', 'from_currency', 'to_currency', 'total_commission',
                  'transfer_rate', 'sending_amount', 'receiving_amount', 'paid_amount', 'due_date',
                  'outstanding_amount', 'total_payment', 'payment_status', 'reason_type', 'notification_type', 'notes')

        widgets = {

            'due_date': forms.DateInput(attrs={'type': 'date'}),
            'notes': forms.Textarea(attrs={'placeholder': 'Write Your Notes'}),

        }

        labels = {

            'sender_agent': 'Sender Agent',
            'receiver_agent': 'Receiver Agent',
            'sender_cu': 'Sender Customer',
            'send_method': 'Sending Method',
            'receive_method': 'Receiving Method',
            'from_currency': 'Sending Currency',
            'to_currency': 'Receiving Currency',
            'total_commission': 'Exchange Rate',
            'transfer_rate': 'Transfer Rate',
            'sending_amount': 'Sending Amount',
            'receiving_amount': 'Receiving Amount',
            'paid_amount': 'Paid Amount',
            'outstanding_amount': 'Outstanding Amount',
            'total_payment': 'Total Payment',
            'payment_status': 'Payment Status',
            'reason_type': 'Reason For Sending',
            'notification_type': 'Notification',
            'notes': 'Notes (optional)',

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.use_custom_control = False
        self.fields['sender_agent'].queryset = MoneyUser.objects.filter(is_agent=True, is_active=True)
        self.fields['sender_cu'].queryset = MoneyUser.objects.filter(is_customer=True, is_active=True)
        self.fields['receiver_agent'].queryset = MoneyUser.objects.filter(is_agent=True, is_active=True)
        self.fields['receiver_cu'].queryset = MoneyUser.objects.filter(is_customer=True, is_active=True)
        # self.fields['to_currency'].queryset = MoneyTransfer.objects.none()
        # self.fields['total_commission'].queryset = MoneyTransfer.objects.none()
        self.helper.layout = Layout(
            HTML("<br>"),
            HTML("<h6 class=card-title> Transaction Details </h6><hr>"),
            Row(
                Column('sender_agent', css_class='form-group col-md-4 mb-3'),
                Column('receiver_agent', css_class='form-group col-md-4 mb-3'),
                Column('send_method', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('sender_cu', css_class='form-group col-md-4 mb-3'),
                Column('receiver_cu', css_class='form-group col-md-4 mb-3'),
                Column('receive_method', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('agent_bank', css_class='form-group col-md-4 mb-3'),
                Column('from_currency', css_class='form-group col-md-4 mb-3'),
                Column('to_currency', css_class='form-group col-md-4 mb-3'),
                css_class='row'
            ),
            Row(
                Column('total_commission', css_class='form-group col-md-4 mb-3'),
                Column('transfer_rate', css_class='form-group col-md-4 mb-3'),

moneytransfer/administration/templates/administration/customer-bank.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{%block title %}Customer Bank{%endblock%}
{% load widget_tweaks %}

{% block breadcrumbs %}

<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Customer Bank</span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <a href="{% url 'administration:add_customer_bank'  %}">
   <button type="btn" class="btn new-add">Add New</button>
   </a>
{% endblock %}

{% block content %} 
<div class="row row-sm mg-b-20">
   <div class="col-sm-12 col-lg-12">
      <div class="card card-table-one">
         <div class="main-title">
            <h6 class="card-title">Customer Banks</h6>
            <!-- filter-mobile-view Start-->
            <div class="filter-mobile-view">
               <button class="btn filter-btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom"><span class="iconify" data-icon="system-uicons:filtering"></span>Filter</button>
               <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
                  <div class="offcanvas-header">
                     <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                  </div>
                  <div class="offcanvas-body small">
                 <form method="get">
                     <div class="row">
                        <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Bank Name</label>
                         {% render_field filter.form.bank_name class="form-control" %}
                 
               </div>
               
               <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Account No</label>
                         {% render_field filter.form.account_no class="form-control" %}
                 
               </div>
               <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Account Name</label>
                         {% render_field filter.form.account_name class="form-control" %}
                 
               </div>
               <div class="col-md-6 col-xl-3 col-sm-12">
                     <div class="filter-field-btn">
                        <button type="submit" class="btn new-add">Search</button>
                        <a href="{% url 'administration:customer_bank'%}" class="btn clear-btn" > Clear All </a>
                     </div>
               </div>
                </div>
                  </form>

                  </div>
               </div>
            </div>
            <!-- filter-mobile-view End-->
         </div>
         <hr />
         <div class="filter-field">
               <form method="get">
                     <div class="row">
                        <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Bank Name</label>
                         {% render_field filter.form.bank_name class="form-control" %}
                 
               </div>
                              <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Account No</label>
                         {% render_field filter.form.account_no class="form-control" %}
                 
               </div>
               <div class="col-md-6 col-xl-3 col-sm-12">
                  <label for="exampleDataList" class="form-label">Search By Account Name</label>
                         {% render_field filter.form.account_name class="form-control" %}
                 
               </div>
               <div class="col-md-6 col-xl-3 col-sm-12">
                     <div class="filter-field-btn">
                        <button type="submit" class="btn new-add">Search</button>
                        <a href="{% url 'administration:customer_bank'%}" class="btn clear-btn" > Clear All </a>
                     </div>
               </div>
                </div>
                  </form>

         </div>
         <div class="table-responsive">
            <table class="table table-hover mg-b-0">
               <thead>
               {%if page_obj %}
                  {% for bank in page_obj %} 
                  <tr>
                     <th>
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
                     </th>
                     <th>ID</th>
                     <th>Bank Name</th>
                     <th>Branch Code</th>
                     <th>Account Name</th>
                     <th>Account No</th>
                     <th>Account Type</th>
                     <th>Short Code</th>
                     <th>Iban</th>
                     <th>Action</th>
                  </tr>
               </thead>
               <tbody id="pageTable">
                  <tr class="table-data">
                     <td>
                        <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
                     </td>
                     <td>{{bank.id}}</td>
                     <td>{{bank.bank_name}}</td>
                     <td>{{bank.bank_branch_code}}</td>
                     <td>{{bank.account_name}}</td>
                     <td>{{bank.account_no}}</td>
                     <td>{{bank.account_type}}</td>
                     <td>{{bank.sort_code}}</td>
                     <td>{{bank.iban}}</td>
                     <td class="action-option">
                        <div class="dropdown">
                           <span class="iconify dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false" data-icon="bi:three-dots"></span>
                           <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                              <li>
                                 <a href="{% url 'administration:view_customer_bank' bank.id %}" class="dropdown-item">View</a>
                              </li>
                              <li>
                                 <a href="{% url 'administration:delete_customer_bank' bank.id %}" class="dropdown-item">Delete</a>
                              </li>
                           </ul>
                        </div>
                     </td>
                  </tr>
               {% endfor %}
                  {% else %}
                  <tr>
                  <td>No Record Found </td>
                  </tr>
               {% endif %}
               </tbody>
            </table>
         </div>
         <!-- table-responsive -->
         <div class="table-pagination">   
            <nav aria-label="Page navigation example">
        <ul class="pagination">
         {% if page_obj.has_previous %}
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a> </li>
         {% endif %}
         {% for i in page_obj.paginator.page_range%}
         {% if page_obj.number == i %}   
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'1' %}
               <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}         
            {% endfor %} 
            {% if page_obj.paginator.num_pages > page_obj.number|add:'1' %}
               <li><a href="?page={{ page_obj.number|add:'1' }}"></a></li>
            {% endif %}  
         {% if page_obj.has_next %}   
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next&hellip;</a> </li>
         {% endif %}      
         </ul>
      </nav>
         </div>
      </div>
   </div>
</div>
{% endblock%}
 {%block js%}
<script>
{% for msg in messages %}
 
Swal.fire(
  'Good job!',
  '{{msg}}',
  'success'
)
{% endfor %}
</script>
{% endblock %}

moneytransfer/administration/templates/administration/faq.html
{% extends 'base/base.html' %}

{% load static %}

{%block title %}FAQ'S{%endblock%}

{% block breadcrumbs %}

<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>FAQ's </span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <a href="{% url 'administration:add_faq'%}">
    <button type="btn" class="btn new-add">Add New</button>
    </a>

{% endblock %}

{% block content %}      
<div class="main-counter">
   <div class="row" >
      <div class="col-md-12 col-sm-12">
         <div class="card">
            <div class="card-body">
               <div class="faq-list">
                  <h6 class="card-title">FAQ's</h6>
                  <hr>
                   {%if faq_list%}
                    {% for faq in faq_list%}    
                  <ul class="accordian-list">  
                  <div class="faq-edit-delete">
                     <ul>
                        <li>
                           <a href="{% url 'administration:edit_faq' faq.id %}"><span class="iconify faq-edit-icon" data-icon="akar-icons:edit"></span></a>
                           <a href="{% url 'administration:delete_faq' faq.id %}"><span class="iconify faq-delete-icon" id="delete" data-icon="fluent:delete-28-regular"></span></a>
                        </li>
                     </ul>
                  </div>        
                     <li class="accordian-item">
                        <input type="checkbox" class="accordian-checkbox" checked>
                        <h2 class="accordian-title"> 
                        {{faq.faq_question}}
                        </h2>
                        <p class="accordian-description">{{faq.faq_answer}}</p>
                     </li>                  
                  </ul>
                   {% endfor %}
                    {% else %}
                    <tr>
                    <td>No Record Found </td>
                    </tr>
                    {% endif %} 
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock%}
{%block js%}
<script>
{% for msg in messages %}
 
Swal.fire(
  'Good job!',
  '{{msg}}',
  'success'
)
{% endfor %}
</script>

{% endblock %}

moneytransfer/administration/templates/administration/view-agent.html
{% extends 'base/base.html' %}

{% load static %}

{%block title %}Agent{%endblock%}

{% block breadcrumbs %}

<li><a href="{% url 'administration:agent' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Agent</span></a></li>
<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>View Agent Profile</span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

  {% for agent in view_agent  %}
<a href="{% url 'administration:edit_agent' agent.id %}"><button type="btn" class="btn new-add">Edit</button></a>
<a href="{% url 'administration:delete_agent' agent.id %}"><button type="btn" class="btn clear-btn">Delete</button></a>
{% endfor %}

{% endblock %}


{% block content %}  
{%if view_agent %}
{% for agent in view_agent  %}
<div class="row row-sm mg-b-20">
   <div class="col-sm-12 col-lg-12">
      <div class="card card-table-one">
         <h6 class="card-title">{{agent.username}}</h6> Agent Profile</h6>
         <hr>
         <div class="view-agent">
            <div class="row">
               <div class="col-md-6 col-sm-12">
                  <div class="border-right">
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Title :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.title_type}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>First Name :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.first_name}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Last Name :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.last_name}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Email :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p><a href="mailto:{{agent.email.url}}">{{agent.email}}</a></p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Mobile Number :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p><a href="tel:{{agent.mobile_no}}">{{agent.mobile_no}}</a></p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Date of Birth :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.dob}}</p>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-md-6 col-sm-12">
                  <div class="border-right">
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Address :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.address}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>City :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.city}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Postal code :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.postal_code}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Country :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.country}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Nationality :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.nationality}}</p>
                        </div>
                     </div>
                     <div class="row">
                        <div class="col-md-4">
                           <p><span>Status :</span></p>
                        </div>
                        <div class="col-md-8">
                           <p>{{agent.status}}</p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endfor %}
{% else %}
<p>No Record Found</p>
{% endif %}
{% endblock%}