moneytransfer/administration/urls.py
from django.urls import path
from administration import views


app_name='administration'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('my-dashboard/', views.my_dashboard,name='my_dashboard'),
    path('logout/', views.logoutUser, name="logout"),
    path('agent/',views.agent_list,name='agent'),
    path('add-new-agent/', views.new_agent,name='add-new-agent'),
    path('view-agent/<int:id>', views.view_agent,name='view_agent'),
    path('edit-agent/<int:id>/', views.edit_agent,name='edit_agent'), # get and post req. for update operation
    path('edit-agent-admin-profile/',views.agentprofile, name='agent_profile'),
    path('edit-customer-admin-profile/',views.customerprofile, name='customer_profile'),
    path('agent-profile-change-password', views.agentchangepassword, name='agent_change_password'),
    path('customer-profile-change-password', views.customerchangepassword, name='customer_change_password'),
    path('delete-agent/delete/<int:id>/',views.delete_agent,name='delete_agent'),
    path('customer/', views.customer_list,name='customer'),
    path('add-new-customer/', views.new_customer,name='add-new-customer'),
    path('view-customer/<int:id>', views.view_customer,name='view_customer'),
    path('edit-customer/<int:id>/', views.edit_customer,name='edit_customer'), # get and post req. for update operation
    path('delete-customer/delete/<int:id>/',views.delete_customer,name='delete_customer'),
    path('currency/', views.currency_list,name='currency'),
    path('add-currency/', views.new_currency,name='add-currency'),
    path('view-currency/<int:id>', views.view_currency,name='view_currency'),
    path('edit-currency/<int:id>/', views.edit_currency,name='edit_currency'), # get and post req. for update operation
    path('delete-currency/delete/<int:id>/',views.delete_currency,name='delete_currency'),
    path('agent-bank/', views.agent_bank,name='agent_bank'),
    path('add-agent-bank/', views.add_agentbank,name='add_agent_bank'),
    path('view-agent-bank/<int:id>', views.view_agentbank,name='view_agent_bank'),
    path('edit-agent-bank/<int:id>/', views.edit_agentbank,name='edit_agent_bank'), # get and post req. for update operation
    path('delete-agent-bank/delete/<int:id>/',views.delete_agentbank,name='delete_agent_bank'),
    path('customer-bank/', views.customer_bank,name='customer_bank'),
    path('add-customer-bank/', views.add_customerbank,name='add_customer_bank'),
    path('view-customer-bank/<int:id>', views.view_customerbank,name='view_customer_bank'),
    path('edit-customer-bank/<int:id>/', views.edit_customerbank,name='edit_customer_bank'), # get and post req. for update operation
    path('delete-customer-bank/delete/<int:id>/',views.delete_customerbank,name='delete_customer_bank'),
    path('reason/',views.reason_list,name='reason'),
    path('add-reason/', views.new_reason,name='new_reason'),
    path('view-reason/<int:id>', views.view_reason,name='view_reason'),
    path('edit-reason/<int:id>/', views.edit_reason,name='edit_reason'), # get and post req. for update operation
    path('delete-reason/delete/<int:id>/',views.delete_reason,name='delete_reason'),
    path('faq/',views.faq_list,name='faq_list'),
    path('add-faq/', views.add_faq,name='add_faq'),
    path('edit-faq/<int:id>/', views.edit_faq,name='edit_faq'), # get and post req. for update operation
    path('delete-faq/delete/<int:id>/',views.delete_faq,name='delete_faq'),
    path('search/',views.GlobalSearchView,name='search'),




]

moneytransfer/customeraccess/urls.py
from django.urls import path
from customeraccess import views

app_name='customeraccess'

urlpatterns = [
    path('faq-list/', views.faq_list,name='faq_list'),
    path('add-receiver/', views.add_receiver,name='add_receiver'),
    path('my-receiver/', views.my_receiver,name='my_receiver'),  
    path('edit-my-receiver/<int:id>/', views.edit_receiver,name='edit_receiver'),
    path('view-my-receiver/<int:id>/',views.view_receiver,name='view_receiver'),
    path('delete-my-receiver/<int:id>/', views.delete_receiver,name='delete_receiver'),
    path('make-new-transaction/', views.make_transaction,name='make_transaction'),
    path('my-transaction-history/', views.my_transaction,name='my_transaction'),
    path('view-my-transaction<int:id>/', views.view_transaction,name='view_transaction'),
    path('track-my-transfer/', views.track_transfer,name='track_transfer'),
    path('track-my-transfer-details/', views.track_details,name='track_details'), 
    path('find-my-nearest-agent/', views.find_agent,name='find_agent'),
    path('find-my-nearest-agent-location/', views.agent_location,name='agent_location'),
    path('logout/', views.logoutCustomer, name="logout"),
    path('under-progress/', views.construction, name="construction"),
    
    


]

moneytransfer/exchange/urls.py
from django.urls import path
from exchange import views

app_name='exchange'

urlpatterns = [
    path('money-exchange/',views.exchange_list,name='money_exchange'),
    path('new-money-exchange/', views.new_exchange,name='new_money_exchange'),
    path('view-money-exchange/<int:id>', views.view_exchange,name='view_exchange'),
    path('edit-exchange/<int:id>/', views.edit_exchange,name='edit_exchange'), # get and post req. for update operation
    path('delete-exchange/delete/<int:id>/',views.delete_exchange,name='delete_exchange'),

]

moneytransfer/moneytransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from administration import views as administration_views
from django.conf.urls import handler404, handler500
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('administration.urls', namespace='administration')),
    path('transfer/',include('transfer.urls', namespace='transfer')),
    path('exchange/',include('exchange.urls', namespace='exchange')),
    path('customer/',include('customeraccess.urls', namespace='customeraccess')),
    path('reset_password/', PasswordResetView.as_view(template_name="auth/password-reset.html"),
         name="password_reset"),
    path('reset_password/done/', PasswordResetDoneView.as_view(template_name="auth/password-reset-done.html"),
         name="password_reset_done"),
    path('reset_password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="auth/password-reset-confirm.html"),
         name="password_reset_confirm"),
    path('reset_password/complete/',
         PasswordResetCompleteView.as_view(template_name="auth/password-reset-complete.html"),
         name="password_reset_complete"),


    
    
]  



handler404 = administration_views.error_404
handler500 = administration_views.error_500

moneytransfer/transfer/urls.py
from django.urls import path
from transfer import views

app_name='transfer'

urlpatterns = [
    path('money-transfer/',views.transfer_list,name='money_transfer'),
    path('new-money-transfer/', views.new_transfer,name='new_money_transfer'),
    path('view-money-transfer/<int:id>', views.view_transfer,name='view_transfer'),
    path('edit-transfer/<int:id>/', views.edit_transfer,name='edit_transfer'), # get and post req. for update operation
    path('delete-transfer/delete/<int:id>/',views.delete_transfer,name='delete_transfer'),
    path('debt-money-transfer/',views.debt_list,name='debt_transfer'),
    path('edit-debt-transfer/<int:id>/', views.edit_debt,name='edit_debt'),
    path('view-debt-transfer/<int:id>', views.view_debt,name='view_debt'),
    path('', views.load_rate,name='load_rate'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here



]

moneytransfer/templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>{%block title %}{% endblock %} </title>
       {% include 'base/css.html' %}
       {%block css%}{% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.ico' %}" />
   </head>
<body>
{% include 'base/side-bar.html' %}
{%block side%}{% endblock %}
<section class="home-section">
      {% include 'base/topbar.html'%}
       <div class="breadcrumbs">
          <div class="breadcrumbs-iteam">
              <ul>
                  <li><a href="{% url 'administration:dashboard'%}"><i class="iconify" data-icon="bx:bx-home-alt"></i></a></li>
                  {%block breadcrumbs%}{% endblock %}
              </ul>
          </div>
          <div class="breadcrumbs-btn">
             {%block breadcrumbsbtn %}{% endblock %}
          </div>
        </div>
        <div class="counter">
          <div class="container-fluid">
              {%block content%}{%endblock%}
          </div>
       </div>
{% include 'base/floating-menu.html'%}
{% include 'base/footer.html'%}
</section>
{% include 'base/js.html'%}
{%block js%}{% endblock %}
</body>
</html>

moneytransfer/templates/base/css.html
{% load  static %}

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet">

<style>
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
</style>

moneytransfer/templates/base/customer-base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
   <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>{%block title %}{% endblock %} </title>
       {% include 'base/customer-css.html' %}
       {%block css%}{% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.ico' %}" />
   </head>
<body>
{% include 'base/customer-side-bar.html' %}
<section class="home-section">
      {% include 'base/customer-topbar.html'%}
       <div class="breadcrumbs">
          <div class="breadcrumbs-iteam">
              <ul>
                  <li><a href="{% url 'administration:my_dashboard'%}"><i class="iconify" data-icon="bx:bx-home-alt"></i></a></li>
                  {%block breadcrumbs%}{% endblock %}
              </ul>
          </div>
          <div class="breadcrumbs-btn">
             {%block breadcrumbsbtn %}{% endblock %}
          </div>
        </div>
        <div class="counter">
          <div class="container-fluid">
              {%block content%}{%endblock%}
          </div>
       </div>
{% include 'base/customer-floating-menu.html'%}
{% include 'base/footer.html'%}
</section>
{% include 'base/js.html'%}
{%block js%}{% endblock %}
</body>
</html>

moneytransfer/templates/base/customer-css.html
{% load  static %}

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/customer.css' %}" rel="stylesheet">
<link href="{% static 'css/select2.min.css' %}" rel="stylesheet">
<style>
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
</style>

moneytransfer/templates/base/customer-floating-menu.html
{% load static %}

<div class="mobile-floting-menu">
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="index.html">Dashboard</a>
        <a href="send-money.html">Send Money</a>
        <a href="track-transfer.html">Track Transfer</a>
        <a href="find-agent.html">Find Nearest Agent</a>
        <a href="my-transaction.html">My Transaction</a>
        <a href="my-receiver.html">My Receivers</a>
    </div>
    <div class="mobile-menu" >
        <ul>
            <li>
                <a> <span class="iconify" data-icon="ci:menu-alt-03" style="font-size:24px;cursor:pointer" onclick="openNav()"></span></a>
                <p>menu</p>
            </li>
            <li>
                <a href="faq.html">
                <span class="iconify" data-icon="ant-design:question-circle-outlined"></span>
                <p>Help</p>
                </a>
            </li>
            <!-- <li><a href="#"><span class="iconify" data-icon="ant-design:user-outlined"></span><p>Admin</p></a></li> -->
            <li>
                <a href="index.html">
                <span  class="iconify" data-icon="bx:bx-home-alt"></span>
                <p>Home</p>
                </a>
            </li>
        </ul>
    </div>
</div>

moneytransfer/templates/base/customer-side-bar.html
{% load static %}
{% if  user.is_active %}
<div class="sidebar">
    <div class="logo-details">
      <i><a href="{% url 'administration:my_dashboard'%}"><img src="{%static 'image/logo-6.png'%}"></a></i>
    <div class="logo_name">Monye Transfer</div>
    <i class='bx bx-menu' id="btn" ></i>
    </div>
    <ul class="nav-list">
    <li>
        <a href="{% url 'administration:my_dashboard'%}">
        <i class='bx bx-grid-alt'></i>
        <span class="links_name">Dashboard</span>
        </a>
        <span class="tooltip">Dashboard</span>
    </li>
    <li>
        <a href="{% url 'customeraccess:make_transaction'%}">
        <i class='bx'>
        <span class="iconify" data-icon="carbon:send-alt"></span>
        </i>
        <span class="links_name">Send Money</span>
        </a>
        <span class="tooltip">Send Money</span>
    </li>
    <li>
        <a href="{% url 'customeraccess:track_transfer'%}" >
        <i class='bx'>
        <span class="iconify" data-icon="clarity:truck-line"></span>
        </i>
        <span class="links_name">Track Transfer</span>
        </a>
        <span class="tooltip">Track Transfer</span>
    </li>
    <li>
        <a href="{% url 'customeraccess:find_agent'%}">
        <i class='bx'>
        <span class="iconify" data-icon="ri:user-search-line"></span>
        </i>
        <span class="links_name">Find Nearest Agent</span>
        </a>
        <span class="tooltip">Find Nearest Agent</span>
    </li>
    <li>
        <a href="{% url 'customeraccess:my_transaction'%}">
        <i class='bx'>
        <span class="iconify" data-icon="bi:clock-history"></span>
        </i>
        <span class="links_name">My Transaction</span>
        </a>
        <span class="tooltip">My Transaction</span>
    </li>
    <li>
        <a href="{% url 'customeraccess:my_receiver'%}">
        <i class='bx'>
        <span class="iconify" data-icon="ph:users-three-light"></span>
        </i>
        <span class="links_name">My Receivers</span>
        </a>
        <span class="tooltip">My Receivers</span>
    </li>
    </ul>
</div>
{%endif%}

moneytransfer/templates/base/customer-topbar.html
{% load static %}

<div class="top-bar">
<div class="top-search">
    <div class="mini-logo">
        <a href="{% url 'administration:my_dashboard' %}"><img src="{% static 'image/logo-6.png'%}" alt="Mini-logo"></a>
    </div>
    <div class="input-group search-group">
        <span class="input-group-text" id="basic-addon1"><i  class="iconify" data-icon="akar-icons:search"></i></span>
        <form>
        <input type="text"class="form-control" placeholder="Search" aria-label="Username" id="search"aria-describedby="basic-addon1">
        </form>
    </div>
</div>
{% for message in messages %}
					<p id="messages">{{message}}</p>
                  {% endfor %}

<div class="admin-login">
    <div class="faqs">
        <a href="{% url 'customeraccess:faq_list'%}"><span class="iconify" data-icon="ant-design:question-circle-outlined"></span>FAQ's</a>
    </div>
    <div class="admin-dropdown">
        <div class="dropdown ">
            <a class="btn" href="#" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="admin-dropdown">
                <img src="{% static 'image/admin.png' %}" class="admin-photo" alt="Admin">
                <div>
                    <h5 class="admin-name">{{user.first_name}}&nbsp;{{user.last_name}}</h5>
                    <p class="admin-name">{{user.user_type}}</p>
                </div>
            </div>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
            <li><a class="dropdown-item" href="{%url 'administration:customer_profile'%}">Profile</a></li>
            <li><a class="dropdown-item" href="{%url 'administration:customer_change_password'%}">Change Password</a></li>
            <li><a class="dropdown-item" href="{% url 'customeraccess:logout'%}">Log Out</a></li>
            </ul>
        </div>
        </div>
    <div>
    </div>
</div>
</div>

moneytransfer/templates/base/floating-menu.html
{% load static %}

<div class="mobile-floting-menu">
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'administration:dashboard'%}">Dashboard</a>
        <a href="{% url 'administration:agent'%}">Agent</a>
        <a href="{% url 'administration:customer'%}">Customer</a>
        <a href="{% url 'transfer:money_transfer'%}">Money Transfer</a>
        <a href="{% url 'transfer:debt_transfer'%}">Debt Money Transfer</a>
        <a href="{% url 'exchange:money_exchange'%}">Money Exchange</a>
        <a href="{% url 'administration:customer_bank' %}">Customer Bank</a>
        <a href="{% url 'administration:agent_bank' %}">Agent Bank</a>
        <a href="{% url 'administration:currency'%}">Currency</a>
        <a href="{% url 'administration:reason'%}">Reasons For Sending</a>
        <a href="">Reports</a>
        </div>
        <div class="mobile-menu" >
        <ul>
            <li>
                <a> <span class="iconify" data-icon="ci:menu-alt-03" style="font-size:24px;cursor:pointer" onclick="openNav()"></span></a>
                <p>menu</p>
            </li>
            <li>
                <a href="faq.html">
                <span class="iconify" data-icon="ant-design:question-circle-outlined"></span>
                <p>FAQ's</p>
                </a>
            </li>
            <!-- <li><a href="#"><span class="iconify" data-icon="ant-design:user-outlined"></span><p>Admin</p></a></li> -->
            <li>
                <a href="{% url 'administration:dashboard'%}">
                <span  class="iconify" data-icon="bx:bx-home-alt"></span>
                <p>Home</p>
                </a>
            </li>
        </ul>
    </div>
</div>            

moneytransfer/templates/base/footer.html
{% load  static %}

<div class="dashboard-footer home-footer">
     <p>2021 ©  Money Transfer</p>
</div>

moneytransfer/templates/base/index.html
{% load  static %}
<!DOCTYPE HTML>
<html>
<head>
     <title>The Coming soon Website Template | Home :: w3layouts</title>
	<link href="{% static 'css/cons.css'%}" rel="stylesheet" type="text/css" media="all" />
	<link href='http://fonts.googleapis.com/css?family=Petit+Formal+Script' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Alegreya+Sans:300,400' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300' rel='stylesheet' type='text/css'>
	</head>
	<body>
	<div class="content">
			<div class="wrap">
				<div class="content-grid">
			<p><img src="{% static 'images/top.png' %}" title=""></p>
				</div>
				<div class="grid">
		<p><img src="{% static 'images/coming.png' %}" title=""></p>
		<h3>We are Still Working on it.</h3>
		
		<form>
									<input type="text" size="30" value="Your Email and Get Notified..." onblur="if (this.value=='') this.value = 'Your Email and Get Notified...'" onfocus="if (this.value=='Your Email and Get Notified...') this.value = ''" name="email" id="email">
									<a href="#"><button class="btn span btn-4 btn-4a icon-arrow-right"><span></span></button></a>
					           
									<div id="response"></div>
									
								</form>
								<div class="clear"></div>
								</div>
		<div class="clear"></div>
		<div class="footer">
		<p>Copyright 2013&nbspTemplate by <a href="http://w3layouts.com"> w3layouts.com</a> </p>
		</div>
		<div class="clear"></div>
		</div>
		</div>
		<div class="clear"></div>
</body>
</html>

moneytransfer/templates/base/js.html
 {% load static %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/iconify.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/select2.min.js' %}"></script>
<script>
    function openNav() {
      document.getElementById("mySidenav").style.width = "100%";
    }
    
    function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
    }

    $(document).ready(function(){
    $("#back-arrow-action").click(function(){
    $("#sidebarMenu").addClass("important");
    });
    });

    
 {% comment %} $(document).ready(function(){
 $('#search').keyup(function(){
 
  // Search text
  var text =   $(this).val();
 
  // Hide all content class element

  $('.content').hide();


  // Search and show
  $('.content:contains("'+text+'")').show();

 });
}); {% endcomment %}

  $(".select").closest("form").on("reset",function(ev){
  var targetJQForm = $(ev.target);
  setTimeout((function(){
      this.find(".select").trigger("change");
  }).bind(targetJQForm),0);

  });
$("#id_country").closest("form").on("reset",function(ev){
  var targetJQForm = $(ev.target);
  setTimeout((function(){
      this.find("#id_country").trigger("change");
  }).bind(targetJQForm),0);

  });
  $(function(){
      'use strict'
      $(document).ready(function(){
        $('.select').select2({
        placeholder: 'Select',
        });
        $('').select2({
        placeholder: 'Select',
        });
        $('.lazyselect').select2({
        placeholder: 'Select',
        });
      });
  });
   
</script>


<script>
$(document).ready(function(){
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#pageTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });

});


</script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
</script>

moneytransfer/templates/base/side-bar.html
{% load static %}
<div class="sidebar">
   <div class="logo-details">
      <i><a href="{% url 'administration:dashboard'%}"><img src="{%static 'image/logo-6.png'%}"></a></i>
    <div class="logo_name">Money Transfer</div>
      <i class='bx bx-menu' id="btn" ></i>
    </div>
    <ul class="nav-list">
    <div class='content'>
    <li>
        <a href="{% url 'administration:dashboard'%}">
        <i class='bx bx-grid-alt'></i>
        <span class="links_name">Dashboard</span>
        </a>
        <span class="tooltip">Dashboard</span>
    </li>
    <div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:agent'%}" id="fuck">
        <i class='bx bx-user'></i>
        <span class="links_name">Agent</span>
        </a>
        <span class="tooltip">Agent</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:customer'%}" id="suck">
        <i class='bx'>
        <span class="iconify" data-icon="ph:users-three"></span>
        </i>
        <span class="links_name">Customer</span>
        </a>
        <span class="tooltip">Customer</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'transfer:money_transfer'%}">
        <i class='bx'>
        <span class="iconify"data-icon="carbon:money"></span>
        </i>
        <span class="links_name">Money Transfer</span>
        </a>
        <span class="tooltip">Money Transfer</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'transfer:debt_transfer'%}">
        <i class='bx'>
        <span class="iconify" data-icon="carbon:money"></span>
        </i>
        <span class="links_name">Debt Money Transfer</span>
        </a>
        <span class="tooltip">Debt Money Transfer</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'exchange:money_exchange'%}">
        <i class='bx'>
        <span class="iconify"  data-icon="carbon:money"></span>
        </i>
        <span class="links_name">Money Exchange</span>
        </a>
        <span class="tooltip">Money Exchange</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:agent_bank' %}">
        <i class='bx'>
        <span class="iconify"  data-icon="mdi-light:bank"></span>
        </i>
        <span class="links_name">Agent Bank</span>
        </a>
        <span class="tooltip">Agent Bank</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:customer_bank' %}">
        <i class='bx'>
        <span class="iconify"   data-icon="mdi-light:bank"></span>
        </i>
        <span class="links_name">Customer Bank</span>
        </a>
        <span class="tooltip">Customer Bank</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:currency'%}">
        <i class='bx'>
        <span class="iconify" data-icon="mdi-light:currency-eur"></span>
        </i>
        <span class="links_name">Currency</span>
        </a>
        <span class="tooltip">Currency</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'administration:reason'%}" class="">
        <i class='bx'>
        <span class="iconify"  data-icon="carbon:send-alt"></span>
        </i>
        <span class="links_name">Reasons For Sending</span>
        </a>
        <span class="tooltip">Reasons For Sending</span>
    </li>
    </div>
    <div class='content'>
    <li>
        <a href="{% url 'customeraccess:construction' %}"id="ulCategory">
        <i class='bx'>
        <span class="iconify" data-icon="iconoir:reports"></span>
        </i>
        <span class="links_name">Reports</span>
        </a>
        <span class="tooltip">Reports</span>
    </li>
    </div>
    </ul>
</div>

moneytransfer/templates/base/topbar.html
{% load static %}

<div class="top-bar">
<div class="top-search">
    <div class="mini-logo">
        <a href="{% url 'administration:dashboard' %}"><img src="{% static 'image/logo-6.png'%}" alt="Mini-logo"></a>
    </div>
    <div class="input-group search-group">
        <span class="input-group-text" id="basic-addon1"><i  class="iconify" data-icon="akar-icons:search"></i></span>
        <form>
        <input type="text"class="form-control" placeholder="Search" aria-label="Username" id="search"aria-describedby="basic-addon1">
        </form>
    </div>
</div>
<div class="admin-login">
    <div class="faqs">
        <a href="{%url 'administration:faq_list'%}"><span class="iconify" data-icon="ant-design:question-circle-outlined"></span>FAQ's</a>
    </div>
    <div class="admin-dropdown">
        <div class="dropdown ">
            <a class="btn" href="#" id="dropdownMenuButton3" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="admin-dropdown">
                <img src="{% static 'image/admin.png' %}" class="admin-photo" alt="Admin">
                <div>
                    <h5 class="admin-name">{{user.first_name}}&nbsp;{{user.last_name}}</h5>
                    <p class="admin-name">{{user.user_type}}</p>
                </div>
            </div>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
            <li><a class="dropdown-item" href="{%url 'administration:agent_profile'%}">Profile</a></li>
            <li><a class="dropdown-item" href="{%url 'administration:agent_change_password'%}">Change Password</a></li>
            <li><a class="dropdown-item" href="{% url 'administration:logout'%}">Log Out</a></li>
            </ul>
        </div>
        </div>
    <div>
    </div>
</div>
</div>
 