moneytransfer/administration/urls.py
from django.urls import path
from administration import views


app_name='administration'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('my-dashboard/', views.my_dashboard,name='my_dashboard'),
    path('logout/', views.logoutUser, name="logout"),
    path('agent/',views.agent_list,name='agent'),
    path('add-new-agent/', views.new_agent,name='add-new-agent'),
    path('view-agent/<int:id>', views.view_agent,name='view_agent'),
    path('edit-agent/<int:id>/', views.edit_agent,name='edit_agent'), # get and post req. for update operation
    path('edit-agent-admin-profile/',views.agentprofile, name='agent_profile'),
    path('edit-customer-admin-profile/',views.customerprofile, name='customer_profile'),
    path('agent-profile-change-password', views.agentchangepassword, name='agent_change_password'),
    path('customer-profile-change-password', views.customerchangepassword, name='customer_change_password'),
    path('delete-agent/delete/<int:id>/',views.delete_agent,name='delete_agent'),
    path('customer/', views.customer_list,name='customer'),
    path('add-new-customer/', views.new_customer,name='add-new-customer'),
    path('view-customer/<int:id>', views.view_customer,name='view_customer'),
    path('edit-customer/<int:id>/', views.edit_customer,name='edit_customer'), # get and post req. for update operation
    path('delete-customer/delete/<int:id>/',views.delete_customer,name='delete_customer'),
    path('currency/', views.currency_list,name='currency'),
    path('add-currency/', views.new_currency,name='add-currency'),
    path('view-currency/<int:id>', views.view_currency,name='view_currency'),
    path('edit-currency/<int:id>/', views.edit_currency,name='edit_currency'), # get and post req. for update operation
    path('delete-currency/delete/<int:id>/',views.delete_currency,name='delete_currency'),
    path('agent-bank/', views.agent_bank,name='agent_bank'),
    path('add-agent-bank/', views.add_agentbank,name='add_agent_bank'),
    path('view-agent-bank/<int:id>', views.view_agentbank,name='view_agent_bank'),
    path('edit-agent-bank/<int:id>/', views.edit_agentbank,name='edit_agent_bank'), # get and post req. for update operation
    path('delete-agent-bank/delete/<int:id>/',views.delete_agentbank,name='delete_agent_bank'),
    path('customer-bank/', views.customer_bank,name='customer_bank'),
    path('add-customer-bank/', views.add_customerbank,name='add_customer_bank'),
    path('view-customer-bank/<int:id>', views.view_customerbank,name='view_customer_bank'),
    path('edit-customer-bank/<int:id>/', views.edit_customerbank,name='edit_customer_bank'), # get and post req. for update operation
    path('delete-customer-bank/delete/<int:id>/',views.delete_customerbank,name='delete_customer_bank'),
    path('reason/',views.reason_list,name='reason'),
    path('add-reason/', views.new_reason,name='new_reason'),
    path('view-reason/<int:id>', views.view_reason,name='view_reason'),
    path('edit-reason/<int:id>/', views.edit_reason,name='edit_reason'), # get and post req. for update operation
    path('delete-reason/delete/<int:id>/',views.delete_reason,name='delete_reason'),
    path('faq/',views.faq_list,name='faq_list'),
    path('add-faq/', views.add_faq,name='add_faq'),
    path('edit-faq/<int:id>/', views.edit_faq,name='edit_faq'), # get and post req. for update operation
    path('delete-faq/delete/<int:id>/',views.delete_faq,name='delete_faq'),
    path('search/',views.GlobalSearchView,name='search'),




]

moneytransfer/customeraccess/urls.py
from django.urls import path
from customeraccess import views

app_name='customeraccess'

urlpatterns = [
    path('faq-list/', views.faq_list,name='faq_list'),
    path('add-receiver/', views.add_receiver,name='add_receiver'),
    path('my-receiver/', views.my_receiver,name='my_receiver'),  
    path('edit-my-receiver/<int:id>/', views.edit_receiver,name='edit_receiver'),
    path('view-my-receiver/<int:id>/',views.view_receiver,name='view_receiver'),
    path('delete-my-receiver/<int:id>/', views.delete_receiver,name='delete_receiver'),
    path('make-new-transaction/', views.make_transaction,name='make_transaction'),
    path('my-transaction-history/', views.my_transaction,name='my_transaction'),
    path('view-my-transaction<int:id>/', views.view_transaction,name='view_transaction'),
    path('track-my-transfer/', views.track_transfer,name='track_transfer'),
    path('track-my-transfer-details/', views.track_details,name='track_details'), 
    path('find-my-nearest-agent/', views.find_agent,name='find_agent'),
    path('find-my-nearest-agent-location/', views.agent_location,name='agent_location'),
    path('logout/', views.logoutCustomer, name="logout"),
    path('under-progress/', views.construction, name="construction"),
    
    


]

moneytransfer/exchange/urls.py
from django.urls import path
from exchange import views

app_name='exchange'

urlpatterns = [
    path('money-exchange/',views.exchange_list,name='money_exchange'),
    path('new-money-exchange/', views.new_exchange,name='new_money_exchange'),
    path('view-money-exchange/<int:id>', views.view_exchange,name='view_exchange'),
    path('edit-exchange/<int:id>/', views.edit_exchange,name='edit_exchange'), # get and post req. for update operation
    path('delete-exchange/delete/<int:id>/',views.delete_exchange,name='delete_exchange'),

]

moneytransfer/moneytransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from administration import views as administration_views
from django.conf.urls import handler404, handler500
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('administration.urls', namespace='administration')),
    path('transfer/',include('transfer.urls', namespace='transfer')),
    path('exchange/',include('exchange.urls', namespace='exchange')),
    path('customer/',include('customeraccess.urls', namespace='customeraccess')),
    path('reset_password/', PasswordResetView.as_view(template_name="auth/password-reset.html"),
         name="password_reset"),
    path('reset_password/done/', PasswordResetDoneView.as_view(template_name="auth/password-reset-done.html"),
         name="password_reset_done"),
    path('reset_password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="auth/password-reset-confirm.html"),
         name="password_reset_confirm"),
    path('reset_password/complete/',
         PasswordResetCompleteView.as_view(template_name="auth/password-reset-complete.html"),
         name="password_reset_complete"),


    
    
]  



handler404 = administration_views.error_404
handler500 = administration_views.error_500

moneytransfer/customeraccess/models.py
from administration.models import CurrencyRate, ReasonType
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django_countries.fields import CountryField
from django.dispatch import receiver
import random


# Create your models here.
"**************************************RECEIVER MODEL************************************"   
def generate_pk():
    number = random.randint(1000, 9999)
    return 'CUTRN{}{}'.format(random.randint(10,55), number)

class Receiver(models.Model):
    TITLE = (
    ('mr', 'Mr.'), 
    ('mrs', 'Mrs.'),
    ('ms', 'Ms.'),
    ('miss', 'Miss.'),
    ('dr', 'Dr.'),
    )
    title_type = models.CharField(choices=TITLE, max_length=30, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=70, null=True)
    email = models.EmailField(unique=True)
    mobile_no = PhoneNumberField(null=True)
    city = models.CharField(max_length=50, null=True)
    country = CountryField()
    account_name = models.CharField(max_length=100, null=True)
    account_no = models.CharField(max_length=100, null=True)
    branch_code = models.CharField(max_length=70, null=True)
    bank_name = models.CharField(max_length=70, null=True)
    bank_contact = PhoneNumberField(null=True, blank=True)
    bank_email = models.EmailField(unique=False,null=True, blank=True)
    description = models.CharField(max_length=150, blank=True)

    def __str__(self):
	    return self.email 

       

"**************************************SEND-MONEY MODEL************************************"   
class SendMoney(models.Model):
    receiver = models.ForeignKey(Receiver, null=True, on_delete=models.CASCADE)
    CURRENCY = (('AED', 'AED'),('ARS', 'ARS'),('AUD', 'AUD'),('BGN', 'BGN'),('BRL', 'BRL'),('BSD', 'BSD'),('CAD', 'CAD'),('CHF', 'CHF'),('CLP', 'CLP'),('CNY', 'CNY'),('COP', 'COP'),('CZK', 'CZK'),('DKK', 'DKK'),('DOP', 'DOP'),('EGP', 'EGP'),('EUR', 'EUR'),('FJD', 'FJD'),('GBP', 'GBP'),('GTQ', 'GTQ'),('HKD', 'HKD'),('HRK', 'HRK'),('HUF', 'HUF'),('IDR', 'IDR'),('ILS', 'ILS'),('INR', 'INR'),('ISK', 'ISK'),('JPY', 'JPY'),('KRW', 'KRW'),('KZT', 'KZT'),('MXN', 'MXN'),('MYR', 'MYR'),('NOK', 'NOK'),('NZD', 'NZD'),('PAB', 'PAB'),('PEN', 'PEN'),('PHP', 'PHP'),('PKR', 'PKR'),('PLN', 'PLN'),('PYG', 'PYG'),('RON', 'RON'),('RUB', 'RUB'),('SAR', 'SAR'),('SEK', 'SEK'),('SAR', 'SAR'),('SGD', 'SGD'),('THB', 'THB'),('TRY', 'TRY'),('TWD', 'TWD'),('UAH', 'UAH'),('USD', 'USD'),('UYU', 'UYU'),('VND', 'VND'),('ZAR', 'ZAR'))
    from_currency = models.CharField(choices=CURRENCY, max_length=5, null=True, blank=True)
    to_currency = models.CharField(choices=CURRENCY, max_length=5, null=True, blank=True)
    our_rate = models.DecimalField(max_digits=15, decimal_places=2)
    send_amount = models.DecimalField(max_digits=15, decimal_places=2) 
    total_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    sending_money = (
        ('bank', 'Bank Transfer'), 
        ('cash', 'Cash Transfer'),
        ('cheque', 'Cheque Transfer'),
        )
    send_method = models.CharField(choices=sending_money, max_length=30, null=True)
    transfer_rate = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    receive_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    account_name = models.CharField(max_length=100, null=True)
    account_no = models.CharField(max_length=100, null=True)
    branch_code = models.CharField(max_length=70, null=True)
    bank_name = models.CharField(max_length=70, null=True)
    bank_contact = PhoneNumberField(null=True, blank=True)
    bank_email = models.EmailField(unique=False,null=True, blank=True)
    receive_method = models.CharField(choices=sending_money, max_length=30, null=True)
    reason_type = models.ForeignKey(ReasonType, null=True, on_delete=models.SET_NULL)
    transaction_id = models.CharField(max_length = 20, default = generate_pk, editable=False)
    trans_status = (
        ('Sent', 'Sent'), 
        ('Ready To Collect', 'Ready To Collect'),
        ('Received', 'Received'),
        ('Cancelled', 'Cancelled'),
        )
    money_status = models.CharField(choices=trans_status, max_length=30, blank=True, default='Sent')
    transaction_date = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=150, blank=True)


    def save(self, *args, **kwargs):
      super().save(*args, **kwargs)
      if not self.transaction_id:            
         self.transaction_id = generate_pk   
         self.save()                                  
    

    def __str__(self):
        return str(self.transaction_id)
    













    

moneytransfer/customeraccess/views.py
# from administration.forms import AgentForm, CustomerForm
from customeraccess.models import Receiver, SendMoney
from administration.models import Faq
from customeraccess.forms import ReceiverForm, SendMoneyForm, EditReceiverForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from customeraccess.filters import ReceiverFilter

# Create your views here.
@login_required(login_url='customeraccess:login')
def my_dashboard(request):
    # receiver = Receiver.objects.all()
    # transaction = SendMoney.objects.all()
    # total_receiver = receiver.count()
    # total_money_transaction = transaction.count()
    # context = {'total_receiver':total_receiver, 'total_money_transaction':total_money_transaction}
    return render(request, "customeraccess/customer-dashboard.html")

@login_required(login_url='customeraccess:login')
def construction(request):
    return render(request, "base/index.html")



# def login_view(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')

#         user = authenticate(request, username=username, password=password)

#         if user is not None:
#             if user.is_customer:
#                 login(request, user)
#                 return redirect('administration:my_dashboard')
#             elif user.is_agent:
#                 login(request, user)
#                 return redirect('administration:dashboard')
#         else:
#             messages.info(request, 'Username OR Password is Incorrect !')

#     context = {}
#     return render(request, 'auth/customer-login-form.html', context)



@login_required(login_url='customeraccess:login')
def add_receiver(request):
    if request.method == "POST":
        form = ReceiverForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('customeraccess:my_receiver')
    else:
        form = ReceiverForm()
    return render(request, 'customeraccess/add-receiver.html', {'form': form})


@login_required(login_url='customeraccess:login')
def my_receiver(request):
    my_receiver = Receiver.objects.all()
    Filter = ReceiverFilter(request.GET, queryset=my_receiver)
    page_obj = Filter.qs
    paginator = Paginator(page_obj, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'my_receiver': Receiver.objects.all(), 'filter': Filter, 'page_obj': page_obj}
    return render(request, "customeraccess/my-receiver.html", context)


@login_required(login_url='customeraccess:login')
def view_receiver(request, id):
    context = {'view_receiver': Receiver.objects.filter(pk=id)}
    return render(request, "customeraccess/view-my-receiver.html", context)


@login_required(login_url='customeraccess:login')
def edit_receiver(request, id):
    receiver = Receiver.objects.get(pk=id)
    form = EditReceiverForm(instance=receiver)
    if request.method == 'POST':
        form = EditReceiverForm(request.POST, instance=receiver)
        if form.is_valid():
            form.save()
            messages.success(request, 'User updated')
            return redirect('customeraccess:my_receiver')
    return render(request, 'customeraccess/edit-my-receiver.html', {'form': form})


@login_required(login_url='customeraccess:login')
def delete_receiver(request, id):
    receiver = Receiver.objects.get(pk=id)
    receiver.delete()
    return redirect('customeraccess:my_receiver')


@login_required(login_url='customeraccess:login')
def make_transaction(request):
    if request.method == "POST":
        form = SendMoneyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('customeraccess:my_transaction')
    else:
        form = SendMoneyForm()
    return render(request, 'customeraccess/send-money.html', {'form': form})


@login_required(login_url='customeraccess:login')
def my_transaction(request):
    context = {'my_transaction': SendMoney.objects.all()}
    return render(request, "customeraccess/my-transaction.html", context)

@login_required(login_url='customeraccess:login')
def view_transaction(request, id):
    context = {'view_transaction': SendMoney.objects.filter(pk=id)}
    return render(request, "customeraccess/view-my-transaction.html", context)


def logoutCustomer(request):
    logout(request)
    return redirect('administration:login')


@login_required(login_url='customeraccess:login')
def track_transfer(request):
    return render(request, "customeraccess/track-transfer.html")


@login_required(login_url='customeraccess:login')
def track_details(request):
    return render(request, "customeraccess/track-transfer-details.html")


@login_required(login_url='customeraccess:login')
def find_agent(request):
    return render(request, "customeraccess/find-agent.html")


@login_required(login_url='customeraccess:login')
def agent_location(request):
    return render(request, "customeraccess/find-nearest-location.html")

@login_required(login_url='administration:login')
def faq_list(request):
    context = {'faq_list': Faq.objects.all()}
    return render(request, "customeraccess/customer-faq-view.html", context)

moneytransfer/customeraccess/templates/customeraccess/customer-faq-view.html
{% extends 'base/customer-base.html' %}

{% load static %}

{%block title %}FAQ'S{%endblock%}

{% comment %} {% block breadcrumbs %}

<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>FAQ's </span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <a href="{% url 'administration:add_faq'%}">
    <button type="btn" class="btn new-add">Add New</button>
    </a>

{% endblock %} {% endcomment %}

{% block content %}      
<div class="main-counter">
   <div class="row" >
      <div class="col-md-12 col-sm-12">
         <div class="card">
            <div class="card-body">
               <div class="faq-list">
                  <h6 class="card-title">FAQ's</h6>
                  <hr>
                   {%if faq_list%}
                    {% for faq in faq_list%}    
                  <ul class="accordian-list">  
                  <div class="faq-edit-delete">
                     {% comment %} <ul>
                        <li>
                           <a href="{% url 'administration:edit_faq' faq.id %}"><span class="iconify faq-edit-icon" data-icon="akar-icons:edit"></span></a>
                           <a href="{% url 'administration:delete_faq' faq.id %}"><span class="iconify faq-delete-icon" data-icon="fluent:delete-28-regular"></span></a>
                        </li>
                     </ul> {% endcomment %}
                  </div>        
                     <li class="accordian-item">
                        <input type="checkbox" class="accordian-checkbox" checked>
                        <h2 class="accordian-title"> 
                        {{faq.faq_question}}
                        </h2>
                        <p class="accordian-description">{{faq.faq_answer}}</p>
                     </li>                  
                  </ul>
                   {% endfor %}
                    {% else %}
                    <tr>
                    <td>No Record Found </td>
                    </tr>
                    {% endif %} 
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
{% endblock%}

moneytransfer/customeraccess/templates/customeraccess/find-agent.html
{% extends 'base/customer-base.html' %}

{% load crispy_forms_tags %}

{%block title %} New Receiver {%endblock%}

{% comment %} {% block breadcrumbs %}

   <li><a href="{% url 'customeraccess:my_receiver' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span> My Receivers </span></a></li>
   <li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Add New Receiver</span></a></li> 

{% endblock %}

   {% block breadcrumbsbtn %} 

      <button form="id-receiverform" type="submit" class="btn new-add">Save</button>
      <button form="id-receiverform" type="reset" class="btn clear-btn">Reset</button>

   {% endblock %} {% endcomment %}

{% block content %} 

   <div class="">
   <div class="row" >
      <div class="col-md-12 col-sm-12">
         <div class="card">
            <div class="card-body">
               <div class="faq-list">
                  <h6 class="card-title">Find Nearest Agent</h6>
                  <hr>
                  <form>
                     <div class="row">
                        <div class="col-md-4">
                           <div class="edit-profile-detail">
                              <div class="">
                                 <label for="country" class="form-label">Search country<sup>*</sup></label>
                                 <select class="form-select form-control" aria-label="country">
                                    <option selected value="India">India </option>
                                    <option value="USA">USA</option>
                                    <option value="SUDAN">SUDAN</option>
                                 </select>
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="edit-profile-detail">
                              <div class="">
                                 <label for="Postal" class="form-label">Postal Code <sup>*</sup></label>
                                 <input type="text" class="form-control" id="Postal" placeholder="Enter Postal">
                              </div>
                           </div>
                        </div>
                        <div class="col-md-4">
                           <div class="edit-profile-detail">
                              <div class="filter-field-btn">
                              <a href="{% url 'customeraccess:agent_location' %}" type="btn" class="btn new-add">
                                 Find Agent
                              </a>
                           </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock%}

{%block js%}

{% endblock %}
 

moneytransfer/customeraccess/templates/customeraccess/my-receiver.html
{% extends 'base/customer-base.html' %}

{% load static %}

{% load widget_tweaks %}

{%block title %} My Receivers {%endblock%}

{% block breadcrumbs %}

  <li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span> My Receivers </span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

    <a href="{% url 'customeraccess:add_receiver' %}" > <button type="btn" class="btn new-add"> Add New </button></a>

{% endblock %}

{% block content %}
   
        <div class="row row-sm mg-b-20">
            <div class="col-sm-12 col-lg-12">
                <div class="card card-table-one">
                <div class="main-title">
                    <h6 class="card-title"> My Receivers List </h6>
                    <!-- filter-mobile-view Start-->
                    <div class="filter-mobile-view">
                        <button class="btn filter-btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom"><span class="iconify" data-icon="system-uicons:filtering"></span>Filter</button>
                        <div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
                            <div class="offcanvas-header">
                            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                            </div>
                            <div class="offcanvas-body small">
                           <form method="get">
                            <div class="row">
                                <div class="col-md-6 col-xl-3 col-sm-12 mb-3">
                                    <label for="exampleDataList" class="form-label">Search By First Name</label>
                                       {% render_field filter.form.first_name class="form-control " %}
                                 
                                </div>
                                <div class="col-md-6 col-xl-3 col-sm-12 mb-3">
                                    <label for="exampleDataList" class="form-label">Search By Account Number</label>
                                     {% render_field filter.form.account_no class="form-control " %}
                                </div>
                                <div class="col-md-6 col-xl-3 col-sm-12 mb-3">
                                    <label for="exampleDataList2" class="form-label">Search By Country</label>
                                     {% render_field filter.form.country class="form-control " %}                 
                                </div>
                                <div class="col-md-6 col-xl-3 col-sm-12">
                                    <div class="filter-field-btn">
                                    <button type="submit" class="btn new-add">Search</button>
                                    <a href="{% url 'customeraccess:my_receiver'%}" class="btn clear-btn" > Clear All </a>
                                 </div>
                                </div>
                            </div>
                            </form>
                            </div>
                        </div>
                    </div>
                    <!-- filter-mobile-view End-->
                </div>
                <hr />
                <div class="filter-field">
                <form method="get">
                    <div class="row">
                        <div class="col-md-6 col-xl-3 col-sm-12">
                            <label for="ID" class="form-label">Search By First Name</label>
                             {% render_field filter.form.first_name class="form-control " %}    
                        </div>
                        <div class="col-md-6 col-xl-3 col-sm-12">
                            <label for="Currency-2" class="form-label">Search By Account Number</label>
                             {% render_field filter.form.account_no class="form-control " %}                         
                        </div>
                        <div class="col-md-6 col-xl-3 col-sm-12">
                            <label for="Nationality" class="form-label">Search By Country</label>
                             {% render_field filter.form.country class="form-control select" %}            
                        </div>
                        <div class="col-md-6 col-xl-3 col-sm-12">
                        <div class="filter-field-btn">
                        <button type="submit" class="btn new-add">Search</button>
                        <a href="{% url 'customeraccess:my_receiver'%}" class="btn clear-btn" > Clear All </a>
                        </div>
                        </div>
                    </div>
                </form>    
                </div>
                </div>
            </div>
        <div class="new-card mt-4">
   <div class="row">
    {%if page_obj %}
      {% for receiver in page_obj  %}
       <div class="col-sm-12 col-md-6 col-xl-4">
         <div class="card">
            <div class="card-body">
               <div class="card-user">
                  <div class="user-info">
                     <div class="user-info__img">
                        <img src="{%static 'image/user.png'%}" alt="Agent">
                     </div>
                     <div class="user-info__basic">
                        <h5 class="mb-6">{{receiver.first_name}}&nbsp;{{receiver.last_name}}</h5>
                     </div>
                  </div>
                  <div class="dropdown">
                     <span class="iconify dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false" data-icon="bi:three-dots"></span>
                     <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                        <li>
                           <a href="{% url 'customeraccess:view_receiver' receiver.id %}" class="dropdown-item"> View </a>
                        </li>
                        <li>
                        </li>
                     </ul>
                  </div>
               </div>
               <div class="agent-contact">
                  <div>
                     <p>Country</p>
                     <h6>{{receiver.country}}</h6>
                  </div>
               </div>
               <div class="agent-contact-status">
                  <div>
                     <p>Mobile Number</p>
                     <h6>{{receiver.mobile_no}}</h6>
                  </div>
               </div>
            </div>
         </div>     
      </div>
   {% endfor %}
   {% else %}
      <tr>
      <td>No Record Found </td>
      </tr>
   {% endif %}
   </div>
   <div class="card-pagination">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
         {% if page_obj.has_previous %}
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a> </li>
         {% endif %}
         {% for i in page_obj.paginator.page_range%}
         {% if page_obj.number == i %}   
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'1' %}
               <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}         
            {% endfor %} 
            {% if page_obj.paginator.num_pages > page_obj.number|add:'1' %}
               <li><a href="?page={{ page_obj.number|add:'1' }}"></a></li>
            {% endif %}  
         {% if page_obj.has_next %}   
            <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next&hellip;</a> </li>
         {% endif %}      
         </ul>
      </nav>
   </div>
</div>

{% endblock%}

{%block js%}
<script>
{% for msg in messages %}
 
Swal.fire(
  'Good job!',
  '{{msg}}',
  'success'
)
{% endfor %}
</script>
{% endblock %}

moneytransfer/customeraccess/templates/customeraccess/send-money.html
{% extends 'base/customer-base.html' %}

{% load crispy_forms_tags %}

{%block title %} Send Money To Receiver {%endblock%}

{% block breadcrumbs %}

   <li><a href="{% url 'customeraccess:my_transaction' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>My Transaction</span></a></li>
   <li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Make Money Transfer</span></li> 

{% endblock %}

{% block breadcrumbsbtn %} 

   <button form="id-sendmoneyform" type="submit" class="btn new-add">Save</button>
   <button form="id-sendmoneyform" type="reset" class="btn clear-btn">Reset</button>

{% endblock %}

{% block content %} 

   <div class="row row-sm mg-b-20">
      <div class="col-sm-12 col-lg-12">
         <div class="card card-table-one">
         <form class="" id="id-sendmoneyform" method="post">
            {% csrf_token %}
            {% crispy form %}
         </form>
         </div>
      </div>
   </div>

{% endblock%}

{%block js%}
<script>
$(document).ready(function() {
    
    $('.form-group').keyup(function () {
        var our = parseFloat($('#id_our_rate').val());
        var transfer = parseFloat($('#id_transfer_rate').val());
        var send = parseFloat($('#id_send_amount').val());
        var receive = parseFloat($('#id_receive_amount').val());
         
        $('#id_receive_amount').val(our * send);
        $('#id_total_amount').val(our + send + transfer);


    });  
  
});
</script>

{% endblock %}
 