moneytransfer/exchange/urls.py
from django.urls import path
from exchange import views

app_name='exchange'

urlpatterns = [
    path('money-exchange/',views.exchange_list,name='money_exchange'),
    path('new-money-exchange/', views.new_exchange,name='new_money_exchange'),
    path('view-money-exchange/<int:id>', views.view_exchange,name='view_exchange'),
    path('edit-exchange/<int:id>/', views.edit_exchange,name='edit_exchange'), # get and post req. for update operation
    path('delete-exchange/delete/<int:id>/',views.delete_exchange,name='delete_exchange'),

]

moneytransfer/moneytransfer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from administration import views as administration_views
from django.conf.urls import handler404, handler500
from django.contrib.auth.views import (PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView,
                                       PasswordResetCompleteView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('administration.urls', namespace='administration')),
    path('transfer/',include('transfer.urls', namespace='transfer')),
    path('exchange/',include('exchange.urls', namespace='exchange')),
    path('customer/',include('customeraccess.urls', namespace='customeraccess')),
    path('reset_password/', PasswordResetView.as_view(template_name="auth/password-reset.html"),
         name="password_reset"),
    path('reset_password/done/', PasswordResetDoneView.as_view(template_name="auth/password-reset-done.html"),
         name="password_reset_done"),
    path('reset_password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="auth/password-reset-confirm.html"),
         name="password_reset_confirm"),
    path('reset_password/complete/',
         PasswordResetCompleteView.as_view(template_name="auth/password-reset-complete.html"),
         name="password_reset_complete"),


    
    
]  



handler404 = administration_views.error_404
handler500 = administration_views.error_500

moneytransfer/transfer/urls.py
from django.urls import path
from transfer import views

app_name='transfer'

urlpatterns = [
    path('money-transfer/',views.transfer_list,name='money_transfer'),
    path('new-money-transfer/', views.new_transfer,name='new_money_transfer'),
    path('view-money-transfer/<int:id>', views.view_transfer,name='view_transfer'),
    path('edit-transfer/<int:id>/', views.edit_transfer,name='edit_transfer'), # get and post req. for update operation
    path('delete-transfer/delete/<int:id>/',views.delete_transfer,name='delete_transfer'),
    path('debt-money-transfer/',views.debt_list,name='debt_transfer'),
    path('edit-debt-transfer/<int:id>/', views.edit_debt,name='edit_debt'),
    path('view-debt-transfer/<int:id>', views.view_debt,name='view_debt'),
    path('', views.load_rate,name='load_rate'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- this one here



]

moneytransfer/transfer/models.py
from typing import Type
from administration.models import Agent, BankUser, CurrencyRate, Customer, MoneyUser, ReasonType
from django.db import models
import random
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver

# Create your models here.
def generate_pk():
    number = random.randint(1000, 9999)
    return 'MTRN{}{}'.format(random.randint(10,55), number)

class MoneyTransfer(models.Model):
    sender_agent = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='sender_agent')
    receiver_agent = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='receiver_agent')
    sending_date = models.DateField(auto_now_add=True)
    sender_cu = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='sender_cu')
    receiver_cu = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='receiver_cu')
    sending_money = (
        ('bank', 'Bank Transfer'), 
        ('cash', 'Cash Transfer'),
        ('cheque', 'Cheque Transfer'),
        ('debt', 'Debt'),
        )
    send_method = models.CharField(choices=sending_money, max_length=30, null=True)
    receiving_money = (
        ('bank', 'Bank Transfer'), 
        ('cash', 'Cash Transfer'),
        ('cheque', 'Cheque Transfer'),
        )
    receive_method = models.CharField(choices=receiving_money, max_length=30, null=True) 
    agent_bank = models.ForeignKey(BankUser, null=True, on_delete=models.SET_NULL, blank=True)
    CURRENCY = (('AED', 'AED'),('ARS', 'ARS'),('AUD', 'AUD'),('BGN', 'BGN'),('BRL', 'BRL'),('BSD', 'BSD'),('CAD', 'CAD'),('CHF', 'CHF'),('CLP', 'CLP'),('CNY', 'CNY'),('COP', 'COP'),('CZK', 'CZK'),('DKK', 'DKK'),('DOP', 'DOP'),('EGP', 'EGP'),('EUR', 'EUR'),('FJD', 'FJD'),('GBP', 'GBP'),('GTQ', 'GTQ'),('HKD', 'HKD'),('HRK', 'HRK'),('HUF', 'HUF'),('IDR', 'IDR'),('ILS', 'ILS'),('INR', 'INR'),('ISK', 'ISK'),('JPY', 'JPY'),('KRW', 'KRW'),('KZT', 'KZT'),('MXN', 'MXN'),('MYR', 'MYR'),('NOK', 'NOK'),('NZD', 'NZD'),('PAB', 'PAB'),('PEN', 'PEN'),('PHP', 'PHP'),('PKR', 'PKR'),('PLN', 'PLN'),('PYG', 'PYG'),('RON', 'RON'),('RUB', 'RUB'),('SAR', 'SAR'),('SEK', 'SEK'),('SAR', 'SAR'),('SGD', 'SGD'),('THB', 'THB'),('TRY', 'TRY'),('TWD', 'TWD'),('UAH', 'UAH'),('USD', 'USD'),('UYU', 'UYU'),('VND', 'VND'),('ZAR', 'ZAR'))
    from_currency = models.CharField(choices=CURRENCY, max_length=5, null=True)
    to_currency = models.CharField(choices=CURRENCY, max_length=5, null=True)
    total_commission = models.ForeignKey(CurrencyRate, null=True, on_delete=models.SET_NULL, related_name='total_commission2')
    transfer_rate = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    transaction_id = models.CharField(max_length = 20, default = generate_pk, editable=False)
    sending_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2) 
    receiving_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2, blank=True)
    due_date = models.DateField(null=True, blank=True)
    outstanding_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    total_payment = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    pay_status = (
        ('sent', 'Sent'), 
        ('processing', 'Processing'), 
        ('delivered', 'Delivered'),
        ('cancelled', 'Cancelled'),
        )
    payment_status = models.CharField(choices=pay_status, max_length=30, null=True, default='Sent')
    reason_type = models.ForeignKey(ReasonType, null=True, on_delete=models.SET_NULL)
    notify = (
        ('sms', 'Sms'), 
        ('email', 'Email'),
        ('both', 'Both'),
        )
    notification_type = models.CharField(choices=notify, max_length=30, null=True)
    notes = models.CharField(max_length=150, blank=True)

    def save(self, *args, **kwargs):
      super().save(*args, **kwargs)
      if not self.transaction_id:                                # if uid of the instance is blank
         self.transaction_id = generate_pk   # generating the uid and allocating the value
         self.save()                                   # saving the instance
          
    
    def __str__(self):
        return str(self.transaction_id)




class DebtTransfer(models.Model):
    debt_id = models.CharField(max_length = 20, null=True, blank=True)
    receiver_customer = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='receiver_customer', blank=True)
    sender_agent = models.ForeignKey(MoneyUser, null=True, on_delete=models.SET_NULL, related_name='sender_agentdb', blank=True)
    receiving_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2, blank=True)
    CURRENCY = (('AED', 'AED'),('ARS', 'ARS'),('AUD', 'AUD'),('BGN', 'BGN'),('BRL', 'BRL'),('BSD', 'BSD'),('CAD', 'CAD'),('CHF', 'CHF'),('CLP', 'CLP'),('CNY', 'CNY'),('COP', 'COP'),('CZK', 'CZK'),('DKK', 'DKK'),('DOP', 'DOP'),('EGP', 'EGP'),('EUR', 'EUR'),('FJD', 'FJD'),('GBP', 'GBP'),('GTQ', 'GTQ'),('HKD', 'HKD'),('HRK', 'HRK'),('HUF', 'HUF'),('IDR', 'IDR'),('ILS', 'ILS'),('INR', 'INR'),('ISK', 'ISK'),('JPY', 'JPY'),('KRW', 'KRW'),('KZT', 'KZT'),('MXN', 'MXN'),('MYR', 'MYR'),('NOK', 'NOK'),('NZD', 'NZD'),('PAB', 'PAB'),('PEN', 'PEN'),('PHP', 'PHP'),('PKR', 'PKR'),('PLN', 'PLN'),('PYG', 'PYG'),('RON', 'RON'),('RUB', 'RUB'),('SAR', 'SAR'),('SEK', 'SEK'),('SAR', 'SAR'),('SGD', 'SGD'),('THB', 'THB'),('TRY', 'TRY'),('TWD', 'TWD'),('UAH', 'UAH'),('USD', 'USD'),('UYU', 'UYU'),('VND', 'VND'),('ZAR', 'ZAR'))
    from_currency = models.CharField(choices=CURRENCY, max_length=5, null=True, blank=True)
    to_currency = models.CharField(choices=CURRENCY, max_length=5, null=True, blank=True)
    total_commission = models.ForeignKey(CurrencyRate, null=True, on_delete=models.SET_NULL, related_name='total_commission1', blank=True)
    sending_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2) 
    receiving_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=20, null=True, decimal_places=2, blank=True)
    due_date = models.DateField(null=True, blank=True)
    outstanding_amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
    sending_money = (
        ('bank', 'Bank Transfer'), 
        ('cash', 'Cash Transfer'),
        ('cheque', 'Cheque Transfer'),
        ('debt', 'Debt'),
        )
    debt = models.CharField(choices=sending_money, max_length=30, null=True, blank=True)

    def __str__(self):
        return str(self.outstanding_amount)


@receiver(post_save, sender=MoneyTransfer)
def create_debt(sender, instance, created, **kwargs):
    if created:
      if instance.receiver_cu or instance.sender_agent or instance.receiving_amount or instance.paid_amount or instance.due_date or instance.outstanding_amount or instance.from_currency or instance.to_currency or instance.total_commission or instance.send_method == 'debt' or instance.transaction_id or instance.sending_amount:
         DebtTransfer.objects.create(receiver_customer = instance.receiver_cu, sender_agent = instance.sender_agent, 
         receiving_amount = instance.receiving_amount, paid_amount = instance.paid_amount, outstanding_amount = instance.outstanding_amount, 
         due_date = instance.due_date, from_currency = instance.from_currency, to_currency = instance.to_currency, 
         total_commission = instance.total_commission, debt = instance.send_method, debt_id = instance.transaction_id, 
         sending_amount = instance.sending_amount,)

moneytransfer/transfer/views.py
from administration.models import CurrencyRate
from transfer.filters import DebtFilter, MoneyFilter
from transfer.models import DebtTransfer, MoneyTransfer
from transfer.forms import DebtTransferForm, MoneyTransferForm, EditMoneyTransferForm
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse


# Create your views here.
@login_required(login_url='administration:login')
def new_transfer(request):
    if request.method == "POST":
        form = MoneyTransferForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('transfer:money_transfer')                     
    else:
        form = MoneyTransferForm()       
    return render(request,'transfer/add-money-transfer.html',{'form':form})

def load_rate(request):
    to_currency = request.GET.get('to_currency')
    currencys = CurrencyRate.objects.all().filter(to_currency=to_currency)
    return render(request, 'transfer/rate.html', {'currencys': currencys})

def load_cities(request):
    from_currency = request.GET.get('from_currency')
    rates = CurrencyRate.objects.all().filter(from_currency=from_currency)
    return render(request, 'transfer/currency.html', {'rates': rates})

@login_required(login_url='administration:login')
def transfer_list(request):
    transfer_list = MoneyTransfer.objects.all()
    Filter = MoneyFilter(request.GET, queryset=transfer_list)
    page_obj = Filter.qs
    paginator = Paginator(page_obj, 10)
    page_number = request.GET.get('page',1)
    page_obj = paginator.get_page(page_number)
    context = {'transfer_list': MoneyTransfer.objects.all(), 'filter': Filter, 'page_obj': page_obj}
    return render(request, "transfer/money-transfer.html", context)


@login_required(login_url='administration:login')
def view_transfer(request, id):
    context = {'view_transfer': MoneyTransfer.objects.filter(pk = id)}
    return render(request, "transfer/view-money-transfer.html", context)



@login_required(login_url='administration:login')
def edit_transfer(request,id):
    transfer = MoneyTransfer.objects.get(pk=id)
    form = EditMoneyTransferForm(instance=transfer)
    if request.method == 'POST':
        form = EditMoneyTransferForm(request.POST, instance=transfer)
        if form.is_valid():
            form.save()
            return redirect('transfer:money_transfer')
    return render(request,'transfer/edit-money-transfer.html',{'form':form})




@login_required(login_url='administration:login')             
def delete_transfer(request,id):
    transfer = MoneyTransfer.objects.get(pk=id)
    transfer.delete()
    return redirect('transfer:money_transfer')


@login_required(login_url='administration:login')
def debt_list(request):
    transfer_list = DebtTransfer.objects.all()
    Filter = DebtFilter(request.GET, queryset=transfer_list)
    page_obj = Filter.qs
    paginator = Paginator(page_obj, 8)
    page_number = request.GET.get('page',1)
    page_obj = paginator.get_page(page_number)
    context = {'transfer_list': DebtTransfer.objects.all(), 'filter': Filter, 'page_obj': page_obj}
    return render(request, "transfer/debt-money-transfer.html", context)

@login_required(login_url='administration:login')
def edit_debt(request,id):
    transfer = DebtTransfer.objects.get(pk=id)
    form = DebtTransferForm(instance=transfer)
    if request.method == 'POST':
        form = DebtTransferForm(request.POST, instance=transfer)
        if form.is_valid():
            form.save(commit=False)
            DebtTransfer.objects.update_or_create(paid_amount=form.cleaned_data['paid_amount'],outstanding_amount=form.cleaned_data['outstanding_amount'],
            receiver_customer=form.cleaned_data['receiver_customer'],sender_agent=form.cleaned_data['sender_agent'], from_currency=form.cleaned_data['from_currency'],
            due_date=form.cleaned_data['due_date'],debt_id=form.cleaned_data['debt_id'], sending_amount=form.cleaned_data['sending_amount'],)
            return redirect('transfer:debt_transfer')
    return render(request,'transfer/edit-debt-money-transfer.html',{'form':form})


@login_required(login_url='administration:login')
def view_debt(request, id):
    context = {'view_debt': DebtTransfer.objects.filter(pk = id)}
    return render(request, "transfer/view-debt-money-transfer.html", context)

moneytransfer/transfer/templates/transfer/add-money-transfer.html
{% extends 'base/base.html' %}

{% load crispy_forms_tags %}

{%block title %}Money Transfer{%endblock%}

{% block breadcrumbs %}

    <li><a href="{% url 'transfer:money_transfer' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Money Transfer</span></a></li>
    <li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span> Add Transfer</span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <button form="id-moneytransferform" type="submit" class="btn new-add">Save</button>
   <button form="id-moneytransferform" type="reset" class="btn clear-btn">Reset</button>

{% endblock %}


{% block content %} 

    <div class="row row-sm mg-b-20">
        <div class="col-sm-12 col-lg-12">
            <div class="card card-table-one">
                <form  method="post" id="id-moneytransferform"  data-cities-url="{% url 'transfer:ajax_load_cities' %}" novalidate>
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>

{% endblock%}
 
{%block js%}
<script>
$(function() {
    if($("#div_id_send_method").val() == 0)
         $("#div_id_outstanding_amount").hide();
         $("#div_id_due_date").hide();
         $("#div_id_paid_amount").hide();
         $("#div_id_agent_bank").hide();
         
});

$("#div_id_send_method").change(function() {
    var selectedVal = $('option:selected', this).text();
    if(selectedVal == "Debt")
    {
        $('#div_id_paid_amount').show();
        $('#div_id_due_date').show();
        $('#div_id_outstanding_amount').show();

    }
    else
    {
        $('#div_id_paid_amount').hide();
        $('#div_id_due_date').hide();
        $('#div_id_outstanding_amount').hide();

    }
});
$("#div_id_send_method").change(function() {
    var selectedVal = $('option:selected', this).text();
    if(selectedVal == "Bank Transfer" || selectedVal == "Cheque Transfer")
    {
         $('#div_id_agent_bank').show();
    }
    else
    {
        $('#div_id_agent_bank').hide();
    }

});

$(document).ready(function() {
    $('.form-group').keyup(function () {
        var amount = parseFloat($('#id_sending_amount').val());
        var exchange = parseFloat($('#id_total_commission').val());
        var transaction = parseFloat($('#id_transfer_rate').val());
        var paid = parseFloat($('#id_paid_amount').val());
        var amount = parseFloat($('#id_sending_amount').val());
        
        $('#id_receiving_amount').val(exchange * amount);
        $('#id_total_payment').val(amount + transaction);
        $('#id_outstanding_amount').val(amount + transaction - paid);


    });
    {% comment %} $('.form-group').change(function () {
        var amount = parseFloat($('#id_sending_amount').val());
        var exchange = parseFloat($('#id_total_commission').val());
        var transaction = parseFloat($('#id_transfer_rate').val());
        var paid = parseFloat($('#id_paid_amount').val());
        var amount = parseFloat($('#id_sending_amount').val());
        
        $('#id_receiving_amount').val(exchange * amount);
        $('#id_total_payment').val(amount + transaction);
        $('#id_outstanding_amount').val(amount + transaction - paid);


    });  
   {% endcomment %}
});
</script>
<script>
    $("#id_from_currency").change(function () {
      var url = $("#id-moneytransferform").attr("data-cities-url");
      var receiving = $(this).val();

      $.ajax({
        url: url,
        data: {
          'from_currency': receiving,
         },
        success: function (data) {
        debugger
          $("#id_to_currency").html(data);
        }
      });

    });
    
    $("#id_to_currency").change(function () {
      var url = '/transfer/'
      var send = $(this).val();

      $.ajax({
        url: url,
        data: {
          'to_currency': send,
         },
        success: function (data) {
          $("#id_total_commission").html(data);
        }
      });

    });
  </script> 
{% endblock %}

moneytransfer/transfer/templates/transfer/currency.html
<option value="" selected="" data-select2-id="18">---------</option>
{% for rate in rates %}
<option value="{{ rate.to_currency}}">{{ rate.to_currency}}</option>
{% endfor %}

moneytransfer/transfer/templates/transfer/edit-debt-money-transfer.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{%block title %}Debt Money Transfer{%endblock%}

{% block breadcrumbs %}

<li><a href="{% url 'transfer:debt_transfer' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Debt Money Transfer</span></a></li>
<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span> Edit Debt Transfer</span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <button type="submit" form="id-moneytransferform" class="btn new-add">Save</button>
   <button type="reset" form="id-moneytransferform" class="btn clear-btn">Reset</button>
{% endblock %}

{% block content %} 


<div class="row row-sm mg-b-20">
   <div class="col-sm-12 col-lg-12">
      <div class="card card-table-one">
      <form  method="post" id="id-moneytransferform"enctype="multipart/form-data">
         {% csrf_token %}
         {% crispy form %}
      </form>
      </div>
   </div>
</div>

{% endblock%}
 
{%block js%}
<script>
   $(function(){
      'use strict'
      $(document).ready(function(){
         $('.select').select2({
         placeholder: 'Select',
         });
         $('.lazyselect').select2({
         placeholder: 'Select',
         });
      });
   });
$(document).ready(function() {  
    $('#id_paid_amount').change(function () {
        var paid = parseFloat($('#id_paid_amount').val());
        var outamount = parseFloat($('#id_outstanding_amount').val());
        
        $('#id_outstanding_amount').val(outamount - paid);

    });   

   
   $("#div_id_sending_currency").hide(); 
   $("#div_id_sender_agent").hide(); 
   $("#div_id_receiver_customer").hide(); 
   $("#div_id_debt_id").hide(); 
   $("#div_id_sending_amount").hide(); 




});

</script>   

{% endblock %}

moneytransfer/transfer/templates/transfer/edit-money-transfer.html
{% extends 'base/base.html' %}
{% load crispy_forms_tags %}

{%block title %}Money Transfer{%endblock%}

{% block breadcrumbs %}

<li><a href="{% url 'transfer:money_transfer' %}"><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span>Money Transfer</span></a></li>
<li><i class="iconify" data-icon="eva:arrow-ios-forward-fill"></i><span> Edit Transfer</span></li>

{% endblock %}

{% block breadcrumbsbtn %} 

   <button form="id-editmoneytransferform" type="submit" class="btn new-add">Save</button>
   <button form="id-editmoneytransferform" type="reset" class="btn clear-btn">Reset</button>

{% endblock %}


{% block content %} 

    <div class="row row-sm mg-b-20">
        <div class="col-sm-12 col-lg-12">
            <div class="card card-table-one">
                <form  method="post" id="id-editmoneytransferform" data-cities-url="{% url 'transfer:load_rate' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% crispy form %}
                </form>
            </div>
        </div>
    </div>

{% endblock%}
 
{%block js%}
<script>
   $(function(){
      'use strict'
      $(document).ready(function(){
         $('.select').select2({
         placeholder: 'Select',
         });
         $('.lazyselect').select2({
         placeholder: 'Select',
         });
      });
   });
</script>
<script>
$("#div_id_send_method").change(function() {
    var selectedVal = $('option:selected', this).text();
    if(selectedVal == "Debt")
    {
         $('#div_id_paid_amount').css('display', 'block');
         $('#div_id_due_date').css('display', 'block');
         $('#div_id_outstanding_amount').css('display', 'block');

    }
    else
    {
        $('#div_id_paid_amount').css('display', 'none');
        $('#div_id_due_date').css('display', 'none');
        $('#div_id_outstanding_amount').css('display', 'none');

    }
});

$("#div_id_send_method").change(function() {
    var selectedVal = $('option:selected', this).text();
    if(selectedVal == "Bank Transfer" || selectedVal == "Cheque Transfer")
    {
         $('#div_id_agent_bank').css('display', 'block');
    }
    else
    {
        $('#div_id_agent_bank').css('display', 'none');
    }

});

$(function() {
    $("#div_id_agent_bank").hide();
    if($("#div_id_send_method").val() == 'debt') //I'm supposing the "Other" option value is 0.
         $("#div_id_outstanding_amount").show();
         $("#div_id_due_date").show();
         $("#div_id_paid_amount").show();
});
$(document).ready(function() {            
   $('#div_id_agent_bank').attr('required', 'required');   
});



</script>

<script>
    $("#id_from_currency").change(function () {
      var url = '/transfer/ajax/load-cities/'
      var receiving = $(this).val();

      $.ajax({
        url: url,
        data: {
          'from_currency': receiving,
         },
        success: function (data) {
          $("#id_to_currency").html(data);
        }
      });

    });
    
    $("#id_to_currency").change(function () {
      var url = '/transfer/'
      var send = $(this).val();

      $.ajax({
        url: url,
        data: {
          'to_currency': send,
         },
        success: function (data) {
                    debugger

          $("#id_total_commission").html(data);
        }
      });

    });
  </script> 
{% endblock %}

moneytransfer/transfer/templates/transfer/rate.html
{% for currency in currencys %}
<option value="{{ currency.total_commission}}">{{ currency.total_commission}}</option>
{% endfor %}